
[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path = 'forge-cache'
script = 'scripts'
#solc = "0.8.13"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
verbosity = 1
sender = '0x4fbe899d37fb7514adf2f41B0630E018Ec275a0C'
tx_origin = '0x4fbe899d37fb7514adf2f41B0630E018Ec275a0C'
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
